### ISSUE TITLE
Question: How to add the extension

### ISSUE THREAD

**Issue by Boriszn** [johnnyqian/enable-font-awesome-site-extension#4]
Hi John, 

Could you please explain how to add this extension into azure web service.

I'm currently struggling with issue with FontAwsome, and Simple Line Icons returning 404. 
And locally all fine but after deploying to Azure receiving this issue, However all fonts there (checked the project folder).
My web app is Angular 4+ ng cli + .net core.

Many Thanks, in advance  
Boris

**Comment by johnnyqian** [comment]
Hi Boris,

Sorry for the late response.

Locate your **App Service** in Azure portal, in the blade, you'll find the "Extensions" tab, in the right pane, click "Add", find "Enable Static Web Fonts", click OK. That's it.

Regards,
Johnny
